config/routes.rb
Rails.application.routes.draw do

  root "shouts#index"
  resources :text_subjects, only: [:create]
  resources :reshout_subjects, only: [:create]
  resources :image_subjects, only: [:create]
  resources :followers, only: [:index]
  resource :search, only: [:show]
  resources :shouts, only: [:index]
  resource :session, only: [:new, :create, :destroy]
  resource :notification, only: [:show]
  resources :users, only: [:new, :create, :index] do
    resource :following_relationship, only: [:create, :destroy]
  end
  get ':username', to: "users#show", as: :user
end

app/models/following_relationship.rb
class FollowingRelationship < ActiveRecord::Base
  belongs_to :followed_user, class_name: "User"
  belongs_to :follower, class_name: "User"

  validate :user_cannot_follow_self

  private
  def user_cannot_follow_self
    if follower_id == followed_user_id
      errors.add(:base, "Users cannot follow themselves")
    end
  end
end

app/models/image_subject.rb
class ImageSubject < ActiveRecord::Base
  has_one :shout, as: :subject
  validates :url, presence: true
end

app/models/reshout_subject.rb
class ReshoutSubject < ActiveRecord::Base
  belongs_to :shout
  # belongs_to :user
end

app/models/shout.rb
class Shout < ActiveRecord::Base
  belongs_to :user
  belongs_to :subject, polymorphic: true, dependent: :destroy
  validates :user_id, presence: true
  validates :subject, presence: true
end

app/models/text_subject.rb
class TextSubject < ActiveRecord::Base
  has_one :shout, as: :subject
  validates :body, presence: true

  def body=(new_body)
    self[:body] = new_body.upcase
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :shouts, dependent: :destroy
  has_many :reshouts, through: :reshouts
  has_many :followed_user_relationships,
    foreign_key: :follower_id,
    class_name: "FollowingRelationship",
    dependent: :destroy
  has_many :followed_users, through: :followed_user_relationships
  has_many :follower_relationships,
    foreign_key: :followed_user_id,
    class_name: "FollowingRelationship",
    dependent: :destroy
  has_many :followers, through: :follower_relationships
  validates :email, presence: true, uniqueness: true
  validates :password_digest, presence: true
  validates :username, presence: true, uniqueness: true

  def follow(user_to_follow)
    followed_users << user_to_follow
  end

  def to_param
    username
  end

  def timeline
    timeline_user_ids = followed_user_ids + [id]
    Shout.where(user_id: timeline_user_ids).order(created_at: :desc).limit(20)
  end

  def unfollow(user_to_unfollow)
    followed_users.destroy(user_to_unfollow)
  end

  def following?(other_user)
    followed_user_ids.include?(other_user.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Monban::ControllerHelpers
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/followers_controller.rb
class FollowersController < ApplicationController
  def index
    @followers = current_user.followers
  end
end

app/controllers/following_relationships_controller.rb
class FollowingRelationshipsController < ApplicationController
  def create
    user_to_follow = User.find_by_username(params[:user_id])
    current_user.follow(user_to_follow)
    redirect_to :back
  end

  def destroy
    user_to_unfollow = User.find_by_username(params[:user_id])
    current_user.unfollow(user_to_unfollow)
    redirect_to :back
  end
end

app/controllers/image_subjects_controller.rb
class ImageSubjectsController < ApplicationController
  def create
    @image_subject = ImageSubject.new(image_subject_params)
    if @image_subject.save
      current_user.shouts.create(subject: @image_subject)
      redirect_to root_path
    else
      @timeline = current_user.timeline.page(params[:page]).per(5)
      @subject = @image_subject
      @image_subject = ImageSubject.new
      @text_subject = TextSubject.new
      render "shouts/index"
    end

  end

  private
  def image_subject_params
    params.require(:image_subject).permit(:url)
  end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  def show
    search_term = "@#{current_user.username}"
    redirect_to search_path(query: search_term)
  end
end

app/controllers/reshout_subjects_controller.rb
class ReshoutSubjectsController < ApplicationController
  def create
    shout_id = params[:shout_id]
    reshout_subject = ReshoutSubject.create(shout_id: shout_id)
    current_user.shouts.create(subject: reshout_subject)

    redirect_to root_path
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def show
    query = params[:query]
    user_search = User.where("username ILIKE ?", "%#{query}%")
    text_search = TextSubject.where("body ILIKE ?", "%#{query}%").map do |subject|
      subject.shout
    end
    image_search = ImageSubject.where("url ILIKE ?", "%#{query}%").map do |subject|
      subject.shout
    end
    @search_results = Kaminari.paginate_array(user_search + text_search + image_search).page(params[:page]).per(3)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def new
  end

  def create
    user = authenticate_session(session_params)

    if sign_in(user)
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end

  private

  def session_params
    params.require(:session).permit(:username, :password)
  end
end

app/controllers/shouts_controller.rb
class ShoutsController < ApplicationController
  before_action :require_login
  def index
    @text_subject = TextSubject.new
    @image_subject = ImageSubject.new
    @timeline = current_user.timeline.page(params[:page]).per(5)
    @subject = @text_subject
  end

end

app/controllers/text_subjects_controller.rb
class TextSubjectsController < ApplicationController
  def create
    @text_subject = TextSubject.new(text_subject_params)
    if @text_subject.save
      current_user.shouts.create(subject: @text_subject)
      redirect_to root_path
    else
      @timeline = current_user.timeline.page(params[:page]).per(5)
      @subject = @text_subject
      @image_subject = ImageSubject.new
      render "shouts/index"
    end
  end

  private
  def text_subject_params
    params.require(:text_subject).permit(:body)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = sign_up(user_params)

    if @user.valid?
      sign_in(@user)
      redirect_to root_path
    else
      render :new
    end
  end

  def index
    @users = User.all
    @following_relationship = FollowingRelationship.new
  end

  def show
    @user = User.find_by_username(params[:username])
    @followed_users = @user.followed_users
    @followers = @user.followers
  end

  private

  def user_params
    params.require(:user).permit(:username,:email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bold_username_helper.rb
module BoldUsernameHelper
  def bold_username(body)
    username_pattern = /@[\w.]+/
    body.gsub(username_pattern) do |username|
      user = load_user(username)
      if user.present?
        link_to username, user
      else
        username
      end
    end
  end

  private

  def clean_name(match)
    match.delete('@').downcase
  end

  def load_user(username)
    User.where("username ILIKE '#{username[1..-1]}'").first
  end


end

app/helpers/feed_helper.rb
module FeedHelper
  def linkify_text_shout(body)
    sanitize bold_username(hashtag(body))
  end
end

app/helpers/gravatar_helper.rb
module GravatarHelper
  def show_gravatar(email)
    email_hash = Digest::MD5.hexdigest(email)
    grav_url = "http://www.gravatar.com/avatar/#{email_hash}"
    image_tag(grav_url, class: "gravatar")
  end
end

app/helpers/hashtag_helper.rb
module HashtagHelper
  def hashtag(body)
    hashtag_pattern = /#\w+/
    body.gsub(hashtag_pattern) do |hashtag|
      link_to hashtag, search_path(query: hashtag[1..-1])
    end
  end
end

app/views/application/_error_messages.html.erb
<% if target.errors.any? %>
  <h3><%= pluralize target.errors.count, "error" %> prevented the form from saving. </h3>
  <ul>
    <% target.errors.full_messages.each do |error| %>
      <li><%= error %></li>
    <% end %>
  </ul>
<% end %>

app/views/image_subjects/_image_subject.html.erb
<%= image_tag image_subject.url %>

app/views/reshout_subjects/_reshout_subject.html.erb
<%= reshout_subject.shout.user.email %> shouted:
<%= render reshout_subject.shout.subject %>

app/views/shouts/_shout.html.erb
<li>
  <div class="shout">
    <%= show_gravatar(shout.user.email) %>
    <%= time_ago_in_words shout.created_at %> ago - <%= render shout.subject %>
    <div class="reshout">
      <%= button_to "re:shout", reshout_subjects_path(shout_id: shout.id) %>
    </div>
  </div>
</li>

app/views/shouts/index.html.erb
<h2> SHOUTS </h2>
<%= render "error_messages", target: @subject %>
<%= form_for @text_subject do |form| %>
  <%= form.label "SHOUT!" %>
  <%= form.text_field :body %>
  <%= form.submit "SHOUT!" %>
<% end %>

<%= form_for @image_subject do |form| %>
  <%= form.label "SHOUT!" %>
  <%= form.text_field :url %>
  <%= form.submit "IMAGE SHOUT!" %>
<% end %>

<h5>Your feed</h5>
<div id="feed">
<ul>
  <%= render @timeline %>
  <%= paginate @timeline %>
</ul>
</div>

app/views/text_subjects/_text_subject.html.erb
<%= sanitize bold_username(hashtag(text_subject.body)) %>

app/views/users/_follow_button.html.erb
<% if user.id != current_user.id %>
  <% if current_user.following?(user) %>
      <%= button_to "Unfollow", [user, :following_relationship], method: :delete %>
  <% else %>
      <%= button_to "Follow", [user, :following_relationship] %>
  <% end %>
<% end %>

app/views/users/_user.html.erb
<li><%= link_to user.username, user %> 
<%= render "users/follow_button", user: user %>
</li>

app/views/users/index.html.erb
<h2>Users</h2>

<ul>
  <%= render @users %>
</ul>

app/views/users/new.html.erb
<%= form_for @user do |form| %>

  <% if @user.errors.any? %>
    <%= pluralize(@user.errors.count, "error") %> prevented your account from being created:
    <ul>
      <% @user.errors.full_messages.each do |error_message| %>
        <li><%= error_message %></li>
      <% end %>
    </ul>
  <% end %>

  <div>
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>
  <div>
    <%= form.label :email %>
    <%= form.email_field :email %>
  <div>
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>
  <div>
    <%= form.submit "Sign up" %>
  </div>
<% end %>

app/views/users/show.html.erb
<h1>Viewing <%= @user.email %>'s profile</h1>
<h2>Users <%= @user.email %> is following</h2>
<%= render @followed_users %>

<h2>Users following <%= @user.email %></h2>
<%= render @followers %>